import requests
import subprocess


# 2 Protein seq from yeastgenome
sample_seq= """>DOG2 YHR043C SGDID:S000001085
MPQFSVDLCLFDLDGTIVSTTTAAESAWKKLCRQHGVDPVELFKHSHGARSQEMMKKFFP
KLDNTDNKGVLALEKDMADNYLDTVSLIPGAENLLLSLDVDTETQKKLPERKWAIVTSGS
PYLAFSWFETILKNVGKPKVFITGFDVKNGKPDPEGYSRARDLLRQDLQLTGKQDLKYVV
FEDAPVGIKAGKAMGAITVGITSSYDKSVLFDAGADYVVCDLTQVSVVKNNENGIVIQVN
NPLTRD*
>HXT12 YIL170W SGDID:S000001432
MGLIVSIFNIGCAIGGIVLSKVGDIYGRRIGLITVTAIYVVGILIQITSINKWYQYFIGR
IISGIGVGGIAVLSPMLISEVAPKHIRGTLVQLYQLMGTMGIFLGYCTNYGTKNYHNATQ
WRVGLGLCFAWATFMVSGMMFVPESPRYLIEVGKDEEAKHSLSKSNKVSVDDPALLAEYD
TIKAGIEIEKLAGNASWSELLSTKTKVFQRVLMGVIIQSLQQLTGDNYFFYYGTTIFKSV
GLKDSFQTSIIIGVVNFFSSFIAVYTIERFGRRTCLLWGAASMLCCFAVFASVGVTKLWP
QGSSHQDITSQGAGNCMIVFTMFFIFSFATTWAGGCFVIVSETFPLRAKSRGMAIATAAN
WMWGFLISFFTPFITGAINFYYGYVFLGCLVFAYFYVFFFVPETKGLTLEEVNTMWLEGV
PAWKSASWVPPERRTADYDADAIDHDNRPIYKRFFSS*
"""

# step 10 & step 11
headers = {
    'Content-Type': 'application/x-www-form-urlencoded',
    'Accept': 'text/plain',
}

data = 'email=test%40gmail.com&title=test&guidetreeout=true&addformats=false&dismatout=false&dealign=false&mbed=true&mbediteration=true&iterations=0&gtiterations=-1&hmmiterations=-1&outfmt=clustal_num&order=aligned&stype=protein&sequence=%3EDOG2%20YHR043C%20SGDID%3AS000001085%0AMPQFSVDLCLFDLDGTIVSTTTAAESAWKKLCRQHGVDPVELFKHSHGARSQEMMKKFFP%0AKLDNTDNKGVLALEKDMADNYLDTVSLIPGAENLLLSLDVDTETQKKLPERKWAIVTSGS%0APYLAFSWFETILKNVGKPKVFITGFDVKNGKPDPEGYSRARDLLRQDLQLTGKQDLKYVV%0AFEDAPVGIKAGKAMGAITVGITSSYDKSVLFDAGADYVVCDLTQVSVVKNNENGIVIQVN%0ANPLTRD*%0A%3EHXT12%20YIL170W%20SGDID%3AS000001432%0AMGLIVSIFNIGCAIGGIVLSKVGDIYGRRIGLITVTAIYVVGILIQITSINKWYQYFIGR%0AIISGIGVGGIAVLSPMLISEVAPKHIRGTLVQLYQLMGTMGIFLGYCTNYGTKNYHNATQ%0AWRVGLGLCFAWATFMVSGMMFVPESPRYLIEVGKDEEAKHSLSKSNKVSVDDPALLAEYD%0ATIKAGIEIEKLAGNASWSELLSTKTKVFQRVLMGVIIQSLQQLTGDNYFFYYGTTIFKSV%0AGLKDSFQTSIIIGVVNFFSSFIAVYTIERFGRRTCLLWGAASMLCCFAVFASVGVTKLWP%0AQGSSHQDITSQGAGNCMIVFTMFFIFSFATTWAGGCFVIVSETFPLRAKSRGMAIATAAN%0AWMWGFLISFFTPFITGAINFYYGYVFLGCLVFAYFYVFFFVPETKGLTLEEVNTMWLEGV%0APAWKSASWVPPERRTADYDADAIDHDNRPIYKRFFSS*'

response = requests.post('https://www.ebi.ac.uk/Tools/services/rest/clustalo/run', headers=headers, data=data)

jobId = response.text

print("jobId:", jobId)

jalview_url = 'https://www.ebi.ac.uk/Tools/services/rest/clustalo/result/'+ jobId+ '/aln-clustal_num'
print("jalview url: ",jalview_url)

# step 12
jalview_exe_path = 'C:\\Users\\chhor\\AppData\\Local\\Jalview\\bin\\jalview.bat'
subprocess.run([jalview_exe_path, "https://www.ebi.ac.uk/Tools/services/rest/clustalo/result/clustalo-R20240709-165430-0694-644924-p1m/aln-clustal_num"], shell = True)