import json
from pathlib import Path

from classes import sequence_similarly_search,  NCIBlASTPlus, JobDispatcherRESTAPI, ClustalOmega, AlphaFoldRESTAPI

# from classes.job_dispatcher import JobDispatcherRESTAPI
# from classes.sequence_similarly_search import NCIBlASTPlus
# from classes.multiple_sequence_alignment import ClustalOmega
PRO_MODEL = AlphaFoldRESTAPI()
SSS = NCIBlASTPlus(job_dispatcher= JobDispatcherRESTAPI('ncbiblast'),check_delay = 10)
MSA = ClustalOmega(job_dispatcher=JobDispatcherRESTAPI('clustalo'))

def main() :

    
    seq = PRO_MODEL.run('A0A1X7R3K2', "output")
    print(seq)

#     seq = """>sp|P54199|MPS1_YEAST Serine/threonine-protein kinase MPS1 OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=MPS1 PE=1 SV=2
# MSTNSFHDYVDLKSRTNTRQFSDDEEFTTPPKLSNFGSALLSHTEKTSASEILSSHNNDK
# IANRLEEMDRSSSRSHPPPSMGNLTSGHTSTSSHSTLFGRYLRNNHQTSMTTMNTSDIEI
# NVGNSLDKSFERIRNLRQNMKEDITAKYAERRSKRFLISNRTTKLGPAKRAMTLTNIFDE
# DVPNSPNQPINARETVELPLEDSHQTNFKETKRNTDYDSIDFGDLNPIQYIKKHNLPTSD
# LPLISQIYFDKQREENRQAALRKHSSRELLYKSRSSSSSLSSNNLLANKDNSITSNNGSQ
# PRRKVSTGSSSSKSSIEIRRALKENIDTSNNSNFNSPIHKIYKGISRNKDSDSEKREVLR
# NISINANHADNLLQQENKRLKRSLDDAITNENINSKNLEVFYHRPAPKPPVTKKVEIVEP
# AKSASLSNNRNIITVNDSQYEKIELLGRGGSSRVYKVKGSGNRVYALKRVSFDAFDDSSI
# DGFKGEIELLEKLKDQKRVIQLLDYEMGDGLLYLIMECGDHDLSQILNQRSGMPLDFNFV
# RFYTKEMLLCIKVVHDAGIVHSDLKPANFVLVKGILKIIDFGIANAVPEHTVNIYRETQI
# GTPNYMAPEALVAMNYTQNSENQHEGNKWKVGRPSDMWSCGCIIYQMIYGKPPYGSFQGQ
# NRLLAIMNPDVKIPFPEHTSNNEKIPKSAIELMKACLYRNPDKRWTVDKVLSSTFLQPFM
# ISGSIMEDLIRNAVRYGSEKPHISQDDLNDVVDTVLRKFADYKI"""
#     # seq= 'MPS1 YDL028C SGDID:S000002186\nMSTNSFHDYVDLKSRTNTRQFSDDEEFTTPPKLSNFGSALLSHTEKTSASEILSSHNNDK\nIANRLEEMDRSSSRSHPPPSMGNLTSGHTSTSSHSTLFGRYLRNNHQTSMTTMNTSDIEI\nNVGNSLDKSFERIRNLRQNMKEDITAKYAERRSKRFLISNRTTKLGPAKRAMTLTNIFDE\nDVPNSPNQPINARETVELPLEDSHQTNFKETKRNTDYDSIDFGDLNPIQYIKKHNLPTSD\nLPLISQIYFDKQREENRQAALRKHSSRELLYKSRSSSSSLSSNNLLANKDNSITSNNGSQ\nPRRKVSTGSSSSKSSIEIRRALKENIDTSNNSNFNSPIHKIYKGISRNKDSDSEKREVLR\nNISINANHADNLLQQENKRLKRSLDDAITNENINSKNLEVFYHRPAPKPPVTKKVEIVEP\nAKSASLSNNRNIITVNDSQYEKIELLGRGGSSRVYKVKGSGNRVYALKRVSFDAFDDSSI\nDGFKGEIELLEKLKDQKRVIQLLDYEMGDGLLYLIMECGDHDLSQILNQRSGMPLDFNFV\nRFYTKEMLLCIKVVHDAGIVHSDLKPANFVLVKGILKIIDFGIANAVPEHTVNIYRETQI\nGTPNYMAPEALVAMNYTQNSENQHEGNKWKVGRPSDMWSCGCIIYQMIYGKPPYGSFQGQ\nNRLLAIMNPDVKIPFPEHTSNNEKIPKSAIELMKACLYRNPDKRWTVDKVLSSTFLQPFM\nISGSIMEDLIRNAVRYGSEKPHISQDDLNDVVDTVLRKFADYKI*\n'
    parameter = "NOT YET IMPLEMENTED"
    # parameter = f'email=test%40gmail.com&title=test&guidetreeout=true&addformats=false&dismatout=false&dealign=false&mbed=true&mbediteration=true&iterations=0&gtiterations=-1&hmmiterations=-1&outfmt=clustal_num&order=aligned&stype=protein&sequence={seq}'
    data = SSS.run(seq, parameter)
#     jsonpath = Path('data' + ".json")
#     # data = jobDispatcher.result('ncbiblast-R20240726-094648-0236-76041824-p1m','json')
#     jsonpath.write_text(json.dumps(data, indent =2))
     
    # data = {
    #     'email': (None, 'test@gmail.com'),
    #     'sequence': (None, '>DOG2 YHR043C SGDID:S000001085\nMPQFSVDLCLFDLDGTIVSTTTAAESAWKKLCRQHGVDPVELFKHSHGARSQEMMKKFFPKLDNTDNKGVLALEKDMADNYLDTVSLIPGAENLLLSLDVDTETQKKLPERKWAIVTSGSPYLAFSWFETILKNVGKPKVFITGFDVKNGKPDPEGYSRARDLLRQDLQLTGKQDLKYVVFEDAPVGIKAGKAMGAITVGITSSYDKSVLFDAGADYVVCDLTQVSVVKNNENGIVIQVNNPLTRD*\n>HXT12 YIL170W SGDID:S000001432\nMGLIVSIFNIGCAIGGIVLSKVGDIYGRRIGLITVTAIYVVGILIQITSINKWYQYFIGRIISGIGVGGIAVLSPMLISEVAPKHIRGTLVQLYQLMGTMGIFLGYCTNYGTKNYHNATQWRVGLGLCFAWATFMVSGMMFVPESPRYLIEVGKDEEAKHSLSKSNKVSVDDPALLAEYDTIKAGIEIEKLAGNASWSELLSTKTKVFQRVLMGVIIQSLQQLTGDNYFFYYGTTIFKSVGLKDSFQTSIIIGVVNFFSSFIAVYTIERFGRRTCLLWGAASMLCCFAVFASVGVTKLWPQGSSHQDITSQGAGNCMIVFTMFFIFSFATTWAGGCFVIVSETFPLRAKSRGMAIATAANWMWGFLISFFTPFITGAINFYYGYVFLGCLVFAYFYVFFFVPETKGLTLEEVNTMWLEGVPAWKSASWVPPERRTADYDADAIDHDNRPIYKRFFSS*'),
    # }
    seq= '>DOG2 YHR043C SGDID:S000001085\nMPQFSVDLCLFDLDGTIVSTTTAAESAWKKLCRQHGVDPVELFKHSHGARSQEMMKKFFPKLDNTDNKGVLALEKDMADNYLDTVSLIPGAENLLLSLDVDTETQKKLPERKWAIVTSGSPYLAFSWFETILKNVGKPKVFITGFDVKNGKPDPEGYSRARDLLRQDLQLTGKQDLKYVVFEDAPVGIKAGKAMGAITVGITSSYDKSVLFDAGADYVVCDLTQVSVVKNNENGIVIQVNNPLTRD*\n>HXT12 YIL170W SGDID:S000001432\nMGLIVSIFNIGCAIGGIVLSKVGDIYGRRIGLITVTAIYVVGILIQITSINKWYQYFIGRIISGIGVGGIAVLSPMLISEVAPKHIRGTLVQLYQLMGTMGIFLGYCTNYGTKNYHNATQWRVGLGLCFAWATFMVSGMMFVPESPRYLIEVGKDEEAKHSLSKSNKVSVDDPALLAEYDTIKAGIEIEKLAGNASWSELLSTKTKVFQRVLMGVIIQSLQQLTGDNYFFYYGTTIFKSVGLKDSFQTSIIIGVVNFFSSFIAVYTIERFGRRTCLLWGAASMLCCFAVFASVGVTKLWPQGSSHQDITSQGAGNCMIVFTMFFIFSFATTWAGGCFVIVSETFPLRAKSRGMAIATAANWMWGFLISFFTPFITGAINFYYGYVFLGCLVFAYFYVFFFVPETKGLTLEEVNTMWLEGVPAWKSASWVPPERRTADYDADAIDHDNRPIYKRFFSS*'
    setting = 'NOT YET IMPLEMENTED'
    print(MSA.run(seq, setting))
if __name__ == '__main__':
    main()