# Test if seq from AlphaFoldRESTAPI is correct
import sys
import os

# Add the root directory to sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../")))

from classes import (
    AlphaFoldRESTAPI,
)
from constants import OUTPUT_FOLDER_PATH

UNIPROT_ENTRY: str = "P54199"
PRO_MODEL = AlphaFoldRESTAPI()
seq, model_path = PRO_MODEL.run(
    unique_id=UNIPROT_ENTRY, output_folder=OUTPUT_FOLDER_PATH
)
assert (
    seq
    == "MSTNSFHDYVDLKSRTNTRQFSDDEEFTTPPKLSNFGSALLSHTEKTSASEILSSHNNDKIANRLEEMDRSSSRSHPPPSMGNLTSGHTSTSSHSTLFGRYLRNNHQTSMTTMNTSDIEINVGNSLDKSFERIRNLRQNMKEDITAKYAERRSKRFLISNRTTKLGPAKRAMTLTNIFDEDVPNSPNQPINARETVELPLEDSHQTNFKETKRNTDYDSIDFGDLNPIQYIKKHNLPTSDLPLISQIYFDKQREENRQAALRKHSSRELLYKSRSSSSSLSSNNLLANKDNSITSNNGSQPRRKVSTGSSSSKSSIEIRRALKENIDTSNNSNFNSPIHKIYKGISRNKDSDSEKREVLRNISINANHADNLLQQENKRLKRSLDDAITNENINSKNLEVFYHRPAPKPPVTKKVEIVEPAKSASLSNNRNIITVNDSQYEKIELLGRGGSSRVYKVKGSGNRVYALKRVSFDAFDDSSIDGFKGEIELLEKLKDQKRVIQLLDYEMGDGLLYLIMECGDHDLSQILNQRSGMPLDFNFVRFYTKEMLLCIKVVHDAGIVHSDLKPANFVLVKGILKIIDFGIANAVPEHTVNIYRETQIGTPNYMAPEALVAMNYTQNSENQHEGNKWKVGRPSDMWSCGCIIYQMIYGKPPYGSFQGQNRLLAIMNPDVKIPFPEHTSNNEKIPKSAIELMKACLYRNPDKRWTVDKVLSSTFLQPFMISGSIMEDLIRNAVRYGSEKPHISQDDLNDVVDTVLRKFADYKI"
)
assert model_path == "output\\protein_model.cif"
